# Generated by Django 6.0.6 on 2026-07-01 06:58

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_collection_usermovieactivity_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.collection_banner_path),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
