# Generated by Django 6.0.6 on 2026-07-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_collection_banner_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieactivity',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
