# Generated by Django 6.0.6 on 2026-07-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_usermovieactivity_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieactivity',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', max_length=10),
        ),
    ]
