# Generated by Django 6.0.6 on 2026-07-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_usermovieactivity_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieactivity',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermovieactivity',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, 'Skip'), (2, 'Timepass'), (3, 'GoForIt'), (4, 'Perfection')], null=True),
        ),
    ]
