# Generated by Django 6.0.6 on 2026-07-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_usermovieactivity_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieactivity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='movies.usermovieactivity'),
        ),
    ]
