# Generated by Django 6.0.6 on 2026-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_usermovieactivity_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieactivity',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
