# Generated by Django 6.0.6 on 2026-07-14 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_usermovieactivity_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovieactivity',
            name='likes',
        ),
        migrations.AddField(
            model_name='usermovieactivity',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
