# Generated by Django 6.0.6 on 2026-07-28 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_usermovieactivity_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermovieactivity',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usermovieactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('user', 'movie_id'), name='unique_user_top_level_movie_review'),
        ),
    ]
