# Generated by Django 6.0.6 on 2026-07-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proile_picture',
            new_name='profile_picture',
        ),
    ]
